"""initial_schema

Revision ID: 3e1719684a0e
Revises: 
Create Date: 2026-05-04 14:33:16.672115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1719684a0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etablissements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('localisation', sa.String(length=255), nullable=False),
    sa.Column('formations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('conditions_admission', sa.Text(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etablissements_nom'), 'etablissements', ['nom'], unique=False)
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('niveau', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('matieres', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('debouches', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('duree', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filieres_nom'), 'filieres', ['nom'], unique=False)
    op.create_table('metiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('competences', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('salaire_moyen', sa.Integer(), nullable=True),
    sa.Column('salaire_debutant', sa.Integer(), nullable=True),
    sa.Column('salaire_experimente', sa.Integer(), nullable=True),
    sa.Column('secteur', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metiers_nom'), 'metiers', ['nom'], unique=False)
    op.create_index(op.f('ix_metiers_secteur'), 'metiers', ['secteur'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('filiere_etablissement',
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('etablissement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filiere_id', 'etablissement_id')
    )
    op.create_table('filiere_metier',
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('metier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metier_id'], ['metiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filiere_id', 'metier_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filiere_metier')
    op.drop_table('filiere_etablissement')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_metiers_secteur'), table_name='metiers')
    op.drop_index(op.f('ix_metiers_nom'), table_name='metiers')
    op.drop_table('metiers')
    op.drop_index(op.f('ix_filieres_nom'), table_name='filieres')
    op.drop_table('filieres')
    op.drop_index(op.f('ix_etablissements_nom'), table_name='etablissements')
    op.drop_table('etablissements')
    # ### end Alembic commands ###
